name: Test package installation

on:
  push:
    branches: [ develop, dev/*, release/* ]
  pull_request:
    branches: [ develop, dev/*, release/* ]
  workflow_dispatch:
    inputs:
      user-to-notify:
        description: "Github username to notify"
        required: false
        default: ""

env:
  NODE_OPTIONS: --max-old-space-size=4096

jobs:
  standard-packages:
    timeout-minutes: 30
    strategy:
      matrix:
        python-versions: [ '3.8', '3.9', '3.10', '3.11', '3.12' ]
        os: [ubuntu-latest, macos-13, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-versions }}

      - name: Install Dependencies
        run: |
          pip install toml

      - name: Build frontends
        run: |
          python tools/frontend/bundle_build.py

      - name: Update pyproject.toml
        run: |
          python tools/release/setup_project.py taipy/config
          python tools/release/setup_project.py taipy/core
          python tools/release/setup_project.py taipy/gui
          python tools/release/setup_project.py taipy/rest
          python tools/release/setup_project.py taipy/templates
          python tools/release/setup_project.py .

      - name: Install Taipy Subpackages
        run: |
          pip install taipy/config taipy/core taipy/gui taipy/rest taipy/templates

      - name: Install Taipy
        run: |
          pip install .

      - name: Remove local folder
        run: rm -r taipy

      - name: Check Taipy Installation
        run: |
          python tools/validate_taipy_install.py

      - name: Notify user if failed
        if: failure()
        run: |
          if [[ -n "${{ github.event.inputs.user-to-notify }}" ]]; then
            curl "${{ secrets.notify_endpoint }}" -d '{"username": "${{ github.event.inputs.user-to-notify }}", "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" }' -H "Content-Type: application/json"
          fi
        shell: bash
